chore: deposit with chain id
consolelabs/mochi-discord pull request #1000
Opened 2023-04-18 08:13 UTC by NguyenHuy1812

**What does this PR do?**

-   [x] deposit with chain id 
![Screenshot 2023-04-18 at 14 47 10](https://user-images.githubusercontent.com/28944972/232713711-5cc4f3b9-ce42-4452-89f6-27f7fc379a70.png)
![Screenshot 2023-04-18 at 14 47 21](https://user-images.githubusercontent.com/28944972/232713720-8da14f18-3769-4e96-86e8-89bf227cdc43.png)
![Screenshot 2023-04-18 at 14 47 31](https://user-images.githubusercontent.com/28944972/232713726-08588884-8f82-4e05-a170-e372f0d45b33.png)
![Screenshot 2023-04-18 at 14 47 41](https://user-images.githubusercontent.com/28944972/232713730-15f0b9cb-4b24-4278-a4db-b2ef52e793bf.png)

-   [x] DM message
- ![Screenshot 2023-04-18 at 14 47 10](https://user-images.githubusercontent.com/28944972/232713470-64e69b55-cc8b-4446-88db-9ca344992186.png)
![Screenshot 2023-04-18 at 14 48 24](https://user-images.githubusercontent.com/28944972/232713733-358e742b-0d58-45da-8268-358e51d05854.png)

2023-04-18 08:39 UTC, trkhoi requested changes

2023-04-18 08:39 UTC, trkhoi commented on src/commands/deposit/index/processor.test.ts
> -import { MessageOptions } from "discord.js"
đang hơi rush thì a cmt lại th, đừng xoá có gì sửa lại test

2023-04-18 08:39 UTC, trkhoi commented on src/commands/deposit/index/slash.test.ts
> -import { slashCommands } from "commands"
same

2023-04-18 08:39 UTC, trkhoi commented on src/commands/deposit/index/text.test.ts
> -import { commands } from "commands"
same

2023-04-18 08:39 UTC, trkhoi commented on src/utils/tip-bot.ts
> +export async function getTokens(symbol: string) {
chỗ này sẽ là gọi api /balances của user -> check xem bals của user có nhiều token trùng ko thì mới show dropdown a, không phải get all tokens từ db

2023-04-18 08:40 UTC, NguyenHuy1812 commented on src/utils/tip-bot.ts
> +export async function getTokens(symbol: string) {
deposit, thì phải get list tokens đó có ở nhiều chain k mới đúng chứ e

2023-04-18 08:47 UTC, NguyenHuy1812 commented on src/commands/deposit/index/processor.test.ts
> -import { MessageOptions } from "discord.js"
<img width="746" alt="Screenshot 2023-04-18 at 15 47 17" src="https://user-images.githubusercontent.com/28944972/232724187-3ea57e3e-7479-4b84-b1a1-f0d9fe7e5b5d.png">
tại cmt thì bị lỗi này k commit lên đc e, any suggest k e?

2023-04-18 08:49 UTC, NguyenHuy1812 commented on src/commands/deposit/index/processor.test.ts
> -import { MessageOptions } from "discord.js"
@trkhoi ^ ở trên nha e

2023-04-19 03:00 UTC, trkhoi requested changes

2023-04-19 03:01 UTC, trkhoi commented on src/commands/deposit/index/processor.test.ts
> -import { MessageOptions } from "discord.js"
cái này chắc nhờ a HA xem gíup

2023-04-19 03:04 UTC, NguyenHuy1812 commented on src/commands/deposit/index/processor.ts
> +    const options: MessageSelectOptionData[] = tokens.map((token: Token) => ({
token này a lấy từ list bên api, nên a nghĩ k cần scope lại đâu e, mấy cía này nên xử lý ở api

2023-04-19 03:07 UTC, NguyenHuy1812 commented on src/commands/deposit/index/processor.test.ts
> -import { MessageOptions } from "discord.js"
@anhnh12 coi giúp a cái này a remove đc k e, nếu k thì cmt kiểu gì để k bị lỗi á

2023-04-19 05:10 UTC, anhnh12 requested changes

2023-04-19 05:10 UTC, anhnh12 commented on src/commands/deposit/index/processor.ts
> +  const tokens = await getTokens(symbol)
use `mochiPay.getTokens()` directly

2023-04-19 05:10 UTC, anhnh12 commented on src/commands/deposit/index/processor.ts
> +  }
duplicated code -> new func

2023-04-19 05:10 UTC, anhnh12 commented on src/commands/deposit/index/processor.ts
> +    }
remove, no need this msg if it's in DM

2023-04-19 05:10 UTC, anhnh12 commented on src/utils/mochi-pay.ts
> +}
remove file

2023-04-19 05:17 UTC, NguyenHuy1812 commented on src/commands/deposit/index/processor.ts
> +    }
DM to replace the select menu

2023-04-19 06:56 UTC, anhnh12 approved these changes

2023-04-19 06:58 UTC, trkhoi approved these changes

2023-04-19 06:58 UTC, merged