chore: airdropoff to airdrop
consolelabs/mochi-discord pull request #536
Opened 2022-10-28 11:05 UTC by hoangharry

**What does this PR do?**

-   [x] Airdropoff to airdrop

**Media (Loom or gif)**
<img width="625" alt="Screen Shot 2022-10-28 at 18 05 22" src="https://user-images.githubusercontent.com/49946656/198572854-31c08dee-3928-4475-a416-d12eba29ce67.png">

2022-10-28 15:25 UTC, trkhoi requested changes

2022-10-28 15:25 UTC, trkhoi commented on src/commands/defi/airdrop.ts
> +            customId: `enter_airdrop_off-${authorId}-${duration}-${maxEntries}`,
t nghĩ là giữ cái `enter_airdrop` nhưng sẽ chỉnh trong `interatiomCreate.ts` chỉ nhận  `enter_airdrop`, không nhận `enter_airdrop_off` nữa

2022-10-31 03:39 UTC, trkhoi approved these changes

2022-10-31 03:47 UTC, catngh approved these changes

2022-10-31 03:52 UTC, merged