chore: nft slash
consolelabs/mochi-discord pull request #538
Opened 2022-10-29 06:15 UTC by catngh

**What does this PR do?**

- Remove author filter for pagination
- slash command for `$nft add / integrate / config twitter-sale`

2022-10-31 03:10 UTC, tuanddd requested changes

2022-10-31 03:10 UTC, tuanddd commented on src/commands/community/nft_slash/config.ts
> +          .setName("access_token")
replace underscore with space

2022-10-31 03:10 UTC, tuanddd commented on src/commands/community/nft_slash/config.ts
> +          .setName("access_token_secret")
replace underscore with space

2022-10-31 03:10 UTC, tuanddd commented on src/commands/community/nft_slash/config.ts
> +    const acsTokenScrt = interaction.options.getString("access_token_secret")
edit to match above and also define the string values upfront at the start of the file and use them below
e.g
```typescript
import .... from ...
import .... from ...

const CONSUMER_KEY = "consumer key"
const CONSUMER_KEY_SECRET = "consumer key secret"
...

// use them below

```

2022-10-31 03:10 UTC, tuanddd commented on src/commands/community/nft_slash/config.ts
> +    console.log(csmrKey, csmrKeyScrt, acsToken, acsTokenScrt)
remove

2022-10-31 03:10 UTC, tuanddd commented on src/commands/community/nft_slash/config.ts
> +  name: "config_twitter-sale",
not presentable to user, use space instead `config twitter sale`

2022-10-31 03:10 UTC, tuanddd commented on src/commands/community/nft_slash/index.ts
> +  "config_twitter-sale": config,
not presentable to user, use space instead `config twitter sale`

2022-10-31 03:44 UTC, catngh commented on src/commands/community/nft_slash/config.ts
> +      .setName("config_twitter-sale")
discord doesn't allow names with spaces, i will make it a subcommand

2022-11-01 03:46 UTC, hoangharry commented on src/utils/discordEmbed.ts
> -      filter: authorFilter(replyMsg.author.id),
cần remove cái này hả e?

2022-11-01 06:54 UTC, tuanddd approved these changes

2022-11-01 07:09 UTC, catngh commented on src/utils/discordEmbed.ts
> -      filter: authorFilter(replyMsg.author.id),
dạ nó làm bug feature qua trang, vẫn work trên button thường

2022-11-01 09:20 UTC, hoangharry approved these changes

2022-11-01 09:29 UTC, merged