chore: add test for reaction role
consolelabs/mochi-discord pull request #754
Opened 2023-02-05 19:43 UTC by haongo138

**What does this PR do?**

-   [x] Add new format testing for reaction roles

2023-02-06 04:34 UTC, trkhoi approved these changes

2023-02-06 05:11 UTC, trkhoi approved these changes

2023-02-06 07:07 UTC, hoangharry approved these changes

2023-02-06 12:12 UTC, anhnh12 requested changes

2023-02-06 12:12 UTC, anhnh12 commented on src/commands/reaction-role/list/processor.ts
> +      if (cfg.roles && cfg.roles.length > 0) {
```suggestion
      if (cfg.roles?.length) {
```

2023-02-06 12:12 UTC, anhnh12 commented on src/commands/reaction-role/list/processor.ts
> +  if (!msg.guildId || !msg.guild) {
no test case for this

2023-02-06 12:12 UTC, anhnh12 commented on src/commands/reaction-role/set/processor.ts
> +  if (!res.ok) {
this could be any error, at least check error status

2023-02-06 12:21 UTC, anhnh12 commented on src/types/common.ts
> +
all API repsonse models should be generated inside `api.ts`
-> remove this
-> remove all reactions role models inside `common.ts`
-> update models in reaction role commands

2023-02-07 05:38 UTC, anhsetel approved these changes

2023-02-07 05:39 UTC, anhnh12 approved these changes

2023-02-07 05:41 UTC, merged