chore: profile remove appellation
consolelabs/mochi-discord pull request #860
Opened 2023-03-09 14:51 UTC by catngh

**What does this PR do?**

- remove appellation

<img width="434" alt="Screenshot 2023-03-09 at 21 50 59" src="https://user-images.githubusercontent.com/84314071/224061500-9e41bf39-a4e2-4f06-920c-614a2309df04.png">

2023-03-09 14:54 UTC, haongo138 approved these changes

2023-03-09 15:24 UTC, trkhoi requested changes

2023-03-09 15:24 UTC, trkhoi commented on src/commands/profile/index/processor.ts
> +    { name: "Activities", value: activityStr, inline: true }
khúc này chắc tạm cmt lại thôi, sau này mình vẫn dùng

2023-03-10 02:09 UTC, trkhoi approved these changes

2023-03-10 02:32 UTC, merged